upstream fastcgi_backend {
    server unix:/var/run/php/php8.5-fpm.sock;
}

server {
    listen 80;
    server_name _;
    set $MAGE_ROOT /var/www/html;
    set $MAGE_MODE developer;

    access_log /var/log/nginx/magento-access.log;
    error_log /var/log/nginx/magento-error.log;

    include /var/www/html/nginx.conf.sample;
}
